// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtimeGUI} from '../models';

export function CheckAdmin():Promise<boolean>;

export function CheckWSL():Promise<boolean>;

export function GetDistroStats():Promise<Array<runtimeGUI.List>>;

export function GetMetrics(arg1:string):Promise<void>;

export function GetPath(arg1:string):Promise<string>;

export function Install_Bottom(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function UninstallDistro(arg1:string):Promise<void>;
