// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDistroStats() {
  return window['go']['main']['App']['GetDistroStats']();
}

export function GetMetrics(arg1) {
  return window['go']['main']['App']['GetMetrics'](arg1);
}

export function GetPath(arg1) {
  return window['go']['main']['App']['GetPath'](arg1);
}

export function Install_Bottom(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Install_Bottom'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UninstallDistro(arg1) {
  return window['go']['main']['App']['UninstallDistro'](arg1);
}
