// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtimeGUI} from '../models';
import {setting} from '../models';
import {main} from '../models';

export function CheckAdmin():Promise<boolean>;

export function CheckAndUpdateWSL():Promise<void>;

export function CheckWSL():Promise<boolean>;

export function GetDistroStats():Promise<Array<runtimeGUI.List>>;

export function GetMetrics(arg1:string):Promise<runtimeGUI.Metrics>;

export function GetPath(arg1:string):Promise<string>;

export function GetPerformanceConfig():Promise<setting.PerformanceConfig>;

export function GetWSLVersion():Promise<string>;

export function Install_Bottom(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function OpenDistroFolder(arg1:string):Promise<void>;

export function SavePerformanceConfig(arg1:setting.PerformanceConfig):Promise<void>;

export function SelectDirectory():Promise<string>;

export function ShowWSLInfo():Promise<string>;

export function StartDistro(arg1:string):Promise<void>;

export function StartMigration(arg1:main.MigrationOptions):Promise<void>;

export function UninstallDistro(arg1:string):Promise<void>;
