// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {runtimeGUI} from '../models';
import {setting} from '../models';
import {main} from '../models';

export function ChangeAPTSource(arg1:string,arg2:string):Promise<string>;

export function CheckAdmin():Promise<boolean>;

export function CheckAndUpdateWSL():Promise<void>;

export function CheckDockerInstalled(arg1:string):Promise<boolean>;

export function CheckWSL():Promise<boolean>;

export function EnableWSLFeature():Promise<void>;

export function GetAPTSource(arg1:string):Promise<string>;

export function GetDistroList():Promise<Array<network.DistroItem>>;

export function GetDistroStats():Promise<Array<runtimeGUI.List>>;

export function GetMetrics(arg1:string):Promise<runtimeGUI.Metrics>;

export function GetPath(arg1:string):Promise<string>;

export function GetPerformanceConfig():Promise<setting.PerformanceConfig>;

export function GetSystemSpecs():Promise<main.SystemSpecs>;

export function GetWSLVersion():Promise<string>;

export function Install_Bottom(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string,arg8:string):Promise<string>;

export function OpenDistroFolder(arg1:string):Promise<void>;

export function SavePerformanceConfig(arg1:setting.PerformanceConfig):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetDockerRegistryMirror(arg1:string,arg2:string):Promise<void>;

export function ShowWSLInfo():Promise<string>;

export function StartDistro(arg1:string):Promise<void>;

export function StartMigration(arg1:main.MigrationOptions):Promise<void>;

export function StopDistro(arg1:string):Promise<void>;

export function TriggerUpdateAlert():Promise<void>;

export function UninstallDistro(arg1:string):Promise<void>;
