// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdmin() {
  return window['go']['main']['App']['CheckAdmin']();
}

export function CheckAndUpdateWSL() {
  return window['go']['main']['App']['CheckAndUpdateWSL']();
}

export function CheckWSL() {
  return window['go']['main']['App']['CheckWSL']();
}

export function GetDistroStats() {
  return window['go']['main']['App']['GetDistroStats']();
}

export function GetMetrics(arg1) {
  return window['go']['main']['App']['GetMetrics'](arg1);
}

export function GetPath(arg1) {
  return window['go']['main']['App']['GetPath'](arg1);
}

export function GetPerformanceConfig() {
  return window['go']['main']['App']['GetPerformanceConfig']();
}

export function GetWSLVersion() {
  return window['go']['main']['App']['GetWSLVersion']();
}

export function Install_Bottom(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Install_Bottom'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function OpenDistroFolder(arg1) {
  return window['go']['main']['App']['OpenDistroFolder'](arg1);
}

export function SavePerformanceConfig(arg1) {
  return window['go']['main']['App']['SavePerformanceConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ShowWSLInfo() {
  return window['go']['main']['App']['ShowWSLInfo']();
}

export function StartMigration(arg1) {
  return window['go']['main']['App']['StartMigration'](arg1);
}

export function UninstallDistro(arg1) {
  return window['go']['main']['App']['UninstallDistro'](arg1);
}

export function StartDistro(arg1) {
  return window['go']['main']['App']['StartDistro'](arg1);
}
