// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeAPTSource(arg1, arg2) {
  return window['go']['main']['App']['ChangeAPTSource'](arg1, arg2);
}

export function CheckAdmin() {
  return window['go']['main']['App']['CheckAdmin']();
}

export function CheckAndUpdateWSL() {
  return window['go']['main']['App']['CheckAndUpdateWSL']();
}

export function CheckDockerInstalled(arg1) {
  return window['go']['main']['App']['CheckDockerInstalled'](arg1);
}

export function CheckWSL() {
  return window['go']['main']['App']['CheckWSL']();
}

export function EnableWSLFeature() {
  return window['go']['main']['App']['EnableWSLFeature']();
}

export function GetAPTSource(arg1) {
  return window['go']['main']['App']['GetAPTSource'](arg1);
}

export function GetDistroList() {
  return window['go']['main']['App']['GetDistroList']();
}

export function GetDistroStats() {
  return window['go']['main']['App']['GetDistroStats']();
}

export function GetMetrics(arg1) {
  return window['go']['main']['App']['GetMetrics'](arg1);
}

export function GetPath(arg1) {
  return window['go']['main']['App']['GetPath'](arg1);
}

export function GetPerformanceConfig() {
  return window['go']['main']['App']['GetPerformanceConfig']();
}

export function GetSystemSpecs() {
  return window['go']['main']['App']['GetSystemSpecs']();
}

export function GetWSLVersion() {
  return window['go']['main']['App']['GetWSLVersion']();
}

export function Install_Bottom(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['Install_Bottom'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function OpenDistroFolder(arg1) {
  return window['go']['main']['App']['OpenDistroFolder'](arg1);
}

export function SavePerformanceConfig(arg1) {
  return window['go']['main']['App']['SavePerformanceConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetDockerRegistryMirror(arg1, arg2) {
  return window['go']['main']['App']['SetDockerRegistryMirror'](arg1, arg2);
}

export function ShowWSLInfo() {
  return window['go']['main']['App']['ShowWSLInfo']();
}

export function StartDistro(arg1) {
  return window['go']['main']['App']['StartDistro'](arg1);
}

export function StartMigration(arg1) {
  return window['go']['main']['App']['StartMigration'](arg1);
}

export function StopDistro(arg1) {
  return window['go']['main']['App']['StopDistro'](arg1);
}

export function UninstallDistro(arg1) {
  return window['go']['main']['App']['UninstallDistro'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}